import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { db } from "@/db/drizzle";
import { projectsAda, promotions } from "@/db/schema";
import { asc } from "drizzle-orm";
import addProject from "./actions/addProject";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themes = await db
    .select({
      title: projectsAda.title,
      slug: projectsAda.slug,
      id: projectsAda.id,
    })
    .from(projectsAda)
    .orderBy(asc(projectsAda.title));

  const promos = await db
    .select({ id: promotions.id, name: promotions.name })
    .from(promotions)
    .orderBy(asc(promotions.name));

  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar themes={themes} promotions={promos} addProject={addProject} />
        <main>{children}</main>
      </body>
    </html>
  );
}
